throw 抛出异常  
try 检查异常  
catch 捕捉异常  
  
  语法格式：  
  ```cpp
    if(发生异常的条件)throw 表达式；
    不发生异常执行的语句

    try
    {
        //被检查的语句
    }
    catch(异常信息类型[异常名])
    {
        //进行异常处理的语句
    }
  ```
  例如：
  ```cpp
    #include "pch.h"
    #include <iostream>
    #include<string.h>
    using namespace std;


    const string ERROR = "error";

    double fun(int x, int y)
    {
        if (y == 0)throw ERROR;
        return x / y;
    }

    int main()
    {
        double s(-1.00);
        int x, y;
        cin >> x >> y;
        try
        {
            s = fun(x, y);
            cout << "顺利执行" << endl << s;
        }
        catch (string)
        {
            cout << "分母为零" << endl << "s=" << s;
        }
        return 0;
    }
  ```